server:
  port:
    8082
spring:
  application:
    name: ordersapp
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    username: 'root'
    url: 'jdbc:mysql://localhost:3306/ordersmsdb'
    password: 'root'
  jpa:
    show_sql: 'true'
    hibernate:
      format_sql: 'true'
      ddl-auto: 'create'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true