openapi: 3.0.0
info:
  title: "The Bookstore API"
  description: "An API to manage Books"
  version: "1.0.0"
servers:
  - url: http://localhost:8080/api/v1
paths:
  /books:
    get:
      summary: "Get a list of all books"
      responses:
        '200':
          description: "A successful list of books"
          content:
            application/json:
               schema:
                 type: array
                 items:
                   $ref: '#/components/schemas/Book'
  /books/{bookId}:
    get:
      summary: "Find a book by its ID"
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
           description: "Book is Found"
        '404':
           description: "Book is not found"

components:
  schemas:
    Book:
      type: object
      required:
        - title
        - author
      properties:
        id:
          type: integer
          example: 100
        title:
          type: string
          example: "A Book"
        author:
           type: string
           example: "Vishwas K Singh"
        available:
           type: boolean
           example: true