openapi: 3.0.0
info:
  title: "The Bookstore API"
  description: "An API to manage Books"
  version: "1.0.0"
servers:
  - url: http://localhost:8080/api/v1
paths:
  /books:
    get:
      summary: "Get a list of all books"
      responses:
        '200':
          description: "A successful list of books"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: "Add a new book"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: "Book added successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '400':
          description: "Invalid input"
          content:
            application/json:
              schema:
                type: object

  /books/{bookId}:
    get:
      summary: "Find a book by its ID"
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: "Book is found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: "Book is not found"
          content:
            application/json:
              schema:
                type: object

    put:
      summary: "Update a book by its ID"
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: "Book Updated successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: "Book not found"
          content:
            application/json:
              schema:
                type: object

    delete:
      summary: "Delete a book by its ID"
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: "Book deleted successfully"
          content: {}
        '404':
          description: "Book not found"
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    Book:
      type: object
      required:
        - title
        - author
      properties:
        id:
          type: integer
          example: 100
        title:
          type: string
          example: "A Book"
        author:
          type: string
          example: "Mayukh Haldar"
        available:
          type: boolean
          example: true
 