app:
    support-email: vishwas@cloudthat.com
server:
    port: 8086
spring:
    application:
        name: addressbookv2
    config:
      import: "aws-secretsmanager:prod/addressbook/mysql"
    cloud:
      aws:
        region:
          static: us-east-1
        credentials:
          instance-profile: true
    datasource:
        driver-class-name: 'com.mysql.cj.jdbc.Driver'
#        username: 'root'
#        url: 'jdbc:mysql://localhost:3306/contactmanagerdb'
#        password: 'root'
        username: ${DB_USER}
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        password: ${DB_PASSWORD}
    jpa:
        show_sql: 'true'
        hibernate:
          format_sql: 'true'
#          ddl-auto: 'create-drop'
          ddl-auto: 'validate'
    mvc:
      problem details:
        enabled: true
logging:
  level:
    root: INFO
    com.cloudthat.services: INFO
  file:
    name: 'logs/app-debug.log'
springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api/v1/api-docs'
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true