server:
  port: 9090
spring:
    application:
        name: apigateway
    cloud:
      gateway:
        server:
          webflux:
            routes:
              - id: ordersapp
                uri: lb://ordersapp
                predicates:
                  - Path=/api/orders/**
              - id: productsapp
                uri: lb://productsapp
                predicates:
                  - Path=/api/products/**
logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health, info

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true